### 问题描述

使用extensions的db会报错，而使用db_helper的db不会
异常为
```
sqlalchemy.exc.InvalidRequestError: Table 'Organization' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

Traceback (most recent call last):
  File "E:\Programming\PersonnelManagement\v.1.1\manage.py", line 16, in <module>
    create_app().run(debug = True)
  File "E:\Programming\PersonnelManagement\v.1.1\app\__init__.py", line 30, in create_app
    init_blueprint(app)
  File "E:\Programming\PersonnelManagement\v.1.1\app\__init__.py", line 72, in init_blueprint
    from controller import organizationBlueprint,dictionaryBlueprint,logBlueprint,employeeBlueprint
  File "E:\Programming\PersonnelManagement\v.1.1\app\controller\__init__.py", line 1, in <module>
    from organization_controller import organizationBlueprint
  File "E:\Programming\PersonnelManagement\v.1.1\app\controller\organization_controller.py", line 14, in <module>
    from models import organization
  File "E:\Programming\PersonnelManagement\v.1.1\app\models\__init__.py", line 1, in <module>
    from organization import Organization,TreeNode
  File "E:\Programming\PersonnelManagement\v.1.1\app\models\organization.py", line 85, in <module>
    class Organization(db.Model):
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 536, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\ext\declarative\api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 116, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 144, in __init__
    self._setup_table()
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 437, in _setup_table
    **table_kw)
  File "E:\Programming\PersonnelManagement\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 438, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'Organization' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

### 问题解决

```python 
class Employee(db.Model):

    __tablename__ = 'Employee'
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer())
```
